app = "meu-bot-fly"
primary_region = "gru"

[build]

[processes]
app = "python bot.py"

[checks]
health = { type = "tcp", port = 8080, interval = "15s", timeout = "2s" }

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
