name: Fly Deploy

on:
  push:
    branches:
      - main  # deploya sempre que houver push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar c√≥digo
        uses: actions/checkout@v3

      - name: Instalar Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"

      - name: Fazer login no Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN

      - name: Deploy no Fly
        run: flyctl deploy --remote-only --config fly.toml
